---
output: jekyllr::jekyll_article
---

```{r, fig.height = 3, warning=F,message=F}
library(ggplot2)
library(hflights)
library(dplyr)
library(ggthemes)

x <- tbl_df(hflights) %>% filter(Month %in% 1:2, Dest %in% c('ABQ', 'AEX', 'BHM', 'BOS')) %>% group_by(Group = ifelse(DayofMonth > 15, 'Desktop', 'Mobile'), Month, Dest, Type = ifelse(DayOfWeek > 3, 'Company', 'Private')) %>% summarise(n = mean(ArrTime, na.rm = T))

x[x$Group == "Desktop" & x$Month == 1 & x$Type == 'Company' & x$Dest == 'BHM',]$n <- 14000
x[x$Group == "Desktop" & x$Month == 2 & x$Type == 'Company' & x$Dest == 'BHM',]$n <- 13000

cols <- c("Company"="#CC6666","Private"="#9999CC")
ggplot(NULL, aes(Dest, n, fill = Type)) +
  geom_bar(data = x %>% filter(Month == 1), stat='identity', alpha = 0.2, width = 0.75) +
  geom_bar(data = x %>% filter(Month == 2), stat='identity', alpha = 1, width = 0.35) +
  geom_point(data = x %>% filter(Month == 2) %>% tally(n) %>% mutate(n = n + runif(1, -1000, 1000)), stat='identity', size = 7.5, fill = 'black', color = 'blue', shape = '|') +
  geom_point(data = x %>% filter(Month == 2) %>% tally(n) %>% mutate(n = n + runif(1, -1000, 1000)), stat='identity', size = 2, fill = 'red', color = "black", shape = 22) +
  coord_flip() +
  facet_wrap(~Group) +
  theme_tufte() +
  theme(legend.position = 'bottom', legend.title = element_blank()) +
  scale_fill_manual(values=cols)
```

### Line (cumulative average) 

```{r, fig.height=3}
x <- tbl_df(hflights) %>% group_by(Year = ifelse(DayofMonth > 15, 'this year', 'previous year'), Type= ifelse(DayOfWeek > 3, 'Company', 'Private'), Month) %>% summarise(n = mean(ArrTime, na.rm = T))
ggplot(NULL, aes(Month, n, color = Type)) +
  geom_hline(yintercept = 1580, linetype = 'dashed', color = 'blue') +
  geom_line(data = x %>% filter(Year == 'this year') %>% group_by(Year, Type) %>% mutate(n = cumsum(n) / Month)) +
  geom_line(data = x %>% filter(Year == 'previous year') %>% group_by(Year, Type) %>% mutate(n = cumsum(n) / Month), alpha = 0.5, linetype = 'dashed') +
  geom_point(data = x %>% filter(Month == 12, Year == 'this year'), size = 2, fill = 'red', color = "black", shape = 22) +
  theme_tufte() +
  theme(legend.position = 'bottom', legend.title = element_blank()) +
  facet_wrap(~Type, ncol = 2, scale = 'free') +
  scale_color_manual(values=cols)
```
